animation :
	gcc animation.c -o animation `pkg-config --cflags gtk+-3.0` `pkg-config --libs glib-2.0` `pkg-config --libs gtk+-3.0` -g -Wall -O3 -std=gnu11

pong :
	gcc pong-ball.c -o pong-ball `pkg-config --cflags gtk+-3.0` `pkg-config --libs glib-2.0` `pkg-config --libs gtk+-3.0` -g -Wall -O3 -std=gnu11

hello :
	gcc hello.c -o hello `pkg-config --cflags gtk+-3.0` `pkg-config --libs glib-2.0` `pkg-config --libs gtk+-3.0` -g -Wall -O3 -std=gnu11

hello_pango :
	gcc hello_pango.c -o hello_pango `pkg-config --cflags gtk+-3.0` `pkg-config --libs glib-2.0` `pkg-config --libs gtk+-3.0` -g -Wall -O3 -std=gnu11
